//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DILG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentID { get; set; }
        public int ReportSubmissionID { get; set; }
        public string Filename { get; set; }
        public byte[] UploadedFile { get; set; }
    
        public virtual ReportSubmission ReportSubmission { get; set; }
    }
}
