//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DILG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportSubmission()
        {
            this.Attachments = new HashSet<Attachment>();
            this.ReportSubmissionHistories = new HashSet<ReportSubmissionHistory>();
        }
    
        public int ReportSubmissionID { get; set; }
        public short SubmittedBy { get; set; }
        public short ReviewidBy { get; set; }
        public short ApprovedBy { get; set; }
        public short ReportTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ReportType ReportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSubmissionHistory> ReportSubmissionHistories { get; set; }
    }
}
