//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DILG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSubmissionHistory
    {
        public int ReportSubmissionHistoryID { get; set; }
        public int ReportSubmissionID { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public short Status { get; set; }
    
        public virtual ReportSubmission ReportSubmission { get; set; }
    }
}
